services:
  flask-app:
    image: telex-commit/intergrator
    container_name: flask-app
    ports:
      - "5000:5000"
    networks:
      - app-network
  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - flask-app
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network
