name: Deploy to Heroku

on:
  push:
    branches:
      - feature/heroku

jobs:
  test:
    uses: ./.github/workflows/ci.yml

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.14
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "github-commit-monitor"
          heroku_email: ${{ secrets.HEROKU_EMAIL }}

      - name: Set Heroku config vars
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          heroku config:set MY_GITHUB_SECRET=${{ secrets.MY_GITHUB_SECRET }} -a github-commit-monitor
          heroku config:set CHANNEL_ID=${{ secrets.CHANNEL_ID }} -a github-commit-monitor
          heroku config:set APP_URL=https://github-commit-monitor-4a53c549b932.herokuapp.com/ -a github-commit-monitor