name: CI

on:
  workflow_call: 
  push:
    branches:
      - main
      - feature/*
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          MY_GITHUB_SECRET: ${{ secrets.MY_GITHUB_SECRET }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
        run: |
          python -m pytest --cov=app tests/ --cov-report=html

      - name: Upload coverage reports
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: htmlcov/